services:
  jupyter-pyspark:
    build: .
    image: jupyter-pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
      - ./jdbc_driver/postgresql-42.7.3.jar:/usr/local/spark/jars/postgresql-42.7.3.jar
      - ./kernels:/usr/local/share/jupyter/kernels
    depends_on:
      - jupyter-pyspark-postgres
  jupyter-pyspark-postgres:
    image: postgres:latest
    container_name: jupyter-pyspark-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jupyter_pyspark_db
    volumes:
      - pyspark-postgres-data:/var/lib/postgresql/data

volumes:
  pyspark-postgres-data:
