services:
  jupyter:
    build: .
    image: pyspark-image
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
      - ./jdbc_driver/postgresql-42.7.3.jar:/usr/local/spark/jars/postgresql-42.7.3.jar
      - ./kernels:/usr/local/share/jupyter/kernels
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: my_username
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
